### ISSUE TITLE
Flipper Crashes due to negative input

### ISSUE THREAD

**Issue by DefinetlyNotAI** [0w0mewo/fpz_cntdown_timer#1]
When putting the timer down to below zero, the application has no safety chack to stop this so it crashes with the generic, Furi_Check Failed

**Comment by 0w0mewo** [comment]
Hey there, thank you for pointing out the issue. 
The codes did clamp the counter to 0 but it still trigger the `furi_check` to fail. Therefore, I simply clamp to 1 instead and it shouldn't crash for now. 

Please let me know if there's a better fix.

**Comment by DefinetlyNotAI** [comment]
So how do i update it? I am new to flipper zero so excuse my novice, and im not really great with C, more of a python type...

**Comment by 0w0mewo** [comment]
> So how do i update it? I am new to flipper zero so excuse my novice, and im not really great with C, more of a python type...

It depends on which firmware you loaded to your flipper zero because you will need to clone the count down timer's source folder and put into firmware source's `application_user` folder, here are example building instructions for official firmware: 

1. clone the firmware source codes or download it from the release: https://github.com/flipperdevices/flipperzero-firmware
2. clone the count down timer source into the `applications_user` of the firmware source.
3. run `fbt fap_cntdown_tim` to build.

There's a detail document from the official doc: https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/AppsOnSDCard.md#how-to-set-up-an-application-to-be-built-as-a-fap-fap-howto
Hopefully it will help you.

**Comment by DefinetlyNotAI** [comment]
Thanks
